r'''
# Déjà Queue

This API documentations was auto-generated by pdoc. See the [readme](https://github.com/danionella/dejaq) on github for a general introduction and overview. 

You can navigate to the API documentation of specific classes and functions on the left.
'''

from .queues import DejaQueue
from .parallel import Parallel