{% set data = load_file_data("../pyproject.toml", from_recipe_dir=True) %}
{% set environment = load_file_data("../environment.yml", from_recipe_dir=True) %}
{% set name = data['project']['name'] %}

package:
  name: {{ name|lower }}
  version: {{ data["project"]["version"] }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ data["project"]["version"] }}.tar.gz
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    {% for dep in environment["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    {% for dep in environment["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    {% for dep in environment["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: {{ data['project']['urls']['Homepage'] }}
  license: MIT
  summary: {{ data['project']['description'] }}

extra:
  recipe-maintainers:
    - benju
